# Generated by Django 4.1.7 on 2023-03-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
