# Generated by Django 4.1.7 on 2023-03-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_Basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
